# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f96a0bc71a0dcc1273e8cf7e473f1d7f3bf2fb7ba1b2a63b95c1aa0de11070c7df0d9082fd2c150e4f5786d12c853e7202429b2e196f6ad50e2f9b74f1c6d0d2

test:
  secret_key_base: 35ea1d67e26a7d5b5ba4377e42a9a5ab0ea1404c72d8621a3fdaf6a1717f578d85246ddd74775df381d89da2667ac1ecd4e3a229695f21d2028a60834cd97f94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
